title: |md
  # Автоматизация сборки
| { near: top-center }

исходный код {shape: page; style.multiple: true}
исходный код -> система сборки -> исполняемый машинный код
система сборки: Система Сборки {
    запуск компилятора -> компиляция
    запуск компоновщика -> линковка
}
исполняемый машинный код {shape: page}