title: |md
  # Процесс сборки исполняемого файла
| { near: top-center }

исходный код {shape: page; style.multiple: true}
объектные файлы {shape: page; style.multiple: true}
исполняемый машинный код {shape: page}
сторонние библиотеки {shape: page; style.multiple: true}

исходный код -> объектные файлы: компиляция
исходный код -> объектные файлы
объектные файлы -> исполняемый машинный код: линковка (компоновка)
сторонние библиотеки -> исполняемый машинный код