direction: right
Парадигмы программирования -> ФП (Функциональное прогр-ние)
ФП (Функциональное прогр-ние) -> Haskell
ФП (Функциональное прогр-ние) -> ML
ФП (Функциональное прогр-ние) -> Clojure
ФП (Функциональное прогр-ние) -> F#
ФП (Функциональное прогр-ние) -> Lua
ФП (Функциональное прогр-ние) -> Ocaml
ФП (Функциональное прогр-ние) -> ELM
ФП (Функциональное прогр-ние) -> Lisp -> Common Lisp
ФП (Функциональное прогр-ние) -> Erlang
ФП (Функциональное прогр-ние) -> Elixir
ФП (Функциональное прогр-ние) -> Scala
ФП (Функциональное прогр-ние) -> Nemerle
ФП (Функциональное прогр-ние) -> Python
Парадигмы программирования -> ООП (Объектно-Ориентированное прогр-ние)
ООП (Объектно-Ориентированное прогр-ние) -> Java
ООП (Объектно-Ориентированное прогр-ние) -> C++
ООП (Объектно-Ориентированное прогр-ние) -> Lua
ООП (Объектно-Ориентированное прогр-ние) -> Perl
ООП (Объектно-Ориентированное прогр-ние) -> Python
ООП (Объектно-Ориентированное прогр-ние) -> D
ООП (Объектно-Ориентированное прогр-ние) -> C#
ООП (Объектно-Ориентированное прогр-ние) -> Kotlin
ООП (Объектно-Ориентированное прогр-ние) -> JavaScript
ООП (Объектно-Ориентированное прогр-ние) -> Ruby
ООП (Объектно-Ориентированное прогр-ние) -> Cobra
Парадигмы программирования -> Процедурное прогр-ние
Процедурное прогр-ние -> Ada
Процедурное прогр-ние -> Basic
Процедурное прогр-ние -> Pascal
Процедурное прогр-ние -> C
Процедурное прогр-ние -> Fortran
Парадигмы программирования -> Логическое прогр-ние
Логическое прогр-ние -> Planner
Planner -> Ether
Planner -> Mercury
Planner -> Datalog
Парадигмы программирования -> Исполнительное прогр-ние
Парадигмы программирования -> Реактивное прогр-ние
Реактивное прогр-ние -> Elm
Реактивное прогр-ние -> Flapjax
Парадигмы программирования -> Декларативное прогр-ние
Декларативное прогр-ние -> HTML + Mercury
Декларативное прогр-ние -> VRML
Декларативное прогр-ние -> SQL
Декларативное прогр-ние -> Mercury
Парадигмы программирования -> Параллельное прогр-ние
Параллельное прогр-ние -> C++
Параллельное прогр-ние -> Java
Параллельное прогр-ние -> Python
Параллельное прогр-ние ->  Go
Парадигмы программирования -> Аспектно-ориентированное прогр-ние
Аспектно-ориентированное прогр-ние -> Java -> AspectJ
Парадигмы программирования -> Структурное прогр-ние
Структурное прогр-ние -> C
Структурное прогр-ние -> C++
Структурное прогр-ние -> Java
Структурное прогр-ние -> Python
Парадигмы программирования -> Аппликативное прогр-ние
Аппликативное прогр-ние -> Lisp -> Clojure
Аппликативное прогр-ние -> ML -> Caml -> Ocaml
Аппликативное прогр-ние -> Haskell
Парадигмы программирования -> Обобщённое прогр-ние
Обобщённое прогр-ние -> C++
Обобщённое прогр-ние -> Haskell
Обобщённое прогр-ние -> Java
Обобщённое прогр-ние -> C#
Обобщённое прогр-ние -> D
Обобщённое прогр-ние -> Object Pascal
Обобщённое прогр-ние -> Nim
Парадигмы программирования -> Порождающее прогр-ние
Парадигмы программирования -> Агентно-ориентированное прогр-ние
Агентно-ориентированное прогр-ние -> Java
Парадигмы программирования -> Контрактное прогр-ние
Контрактное прогр-ние -> Ada
Контрактное прогр-ние -> Clojure
Контрактное прогр-ние -> Cobra
Контрактное прогр-ние -> Component Pascal
Контрактное прогр-ние -> D
Контрактное прогр-ние -> Eiffel
Контрактное прогр-ние -> Fortress
Парадигмы программирования -> Автоматное прогр-ние
Парадигмы программирования -> Событийно-ориентированное прогр-ние
Событийно-ориентированное прогр-ние -> JavaScript
Событийно-ориентированное прогр-ние -> Java
Событийно-ориентированное прогр-ние -> Python
Событийно-ориентированное прогр-ние -> Perl
Событийно-ориентированное прогр-ние -> C++
Событийно-ориентированное прогр-ние -> Tcl
Событийно-ориентированное прогр-ние -> PHP
Событийно-ориентированное прогр-ние ->  Objective-C
Парадигмы программирования -> Компонентно-ориентированное прогр-ние
Компонентно-ориентированное прогр-ние -> Ada
Компонентно-ориентированное прогр-ние -> Java
Компонентно-ориентированное прогр-ние -> C#
Компонентно-ориентированное прогр-ние -> Oberon
Компонентно-ориентированное прогр-ние -> Component Pascal

Lisp -> Scheme
Lisp -> Racket